Bug 2067820: Update prometheus client_golang from 1.11.0 => 1.11.1
openshift/openshift-controller-manager pull request #219
Opened 2022-04-05 16:42 UTC by coreydaley

Mitigates CVE-2022-21698

2022-04-05 16:42 UTC, coreydaley commented
/assign @adambkaplan @gabemontero

2022-04-05 17:08 UTC, coreydaley commented
/retest required

2022-04-05 17:14 UTC, coreydaley commented
/retest-required

2022-04-05 18:54 UTC, coreydaley commented
/retest

2022-04-05 20:21 UTC, coreydaley commented
/retest

2022-04-06 15:51 UTC, gabemontero commented
/lgtm

2022-04-06 17:14 UTC, adambkaplan requested changes
/lgtm cancel

2022-04-06 17:14 UTC, adambkaplan commented on go.mod
> +	github.com/prometheus/client_golang => github.com/prometheus/client_golang v1.11.1 // CVE-2022-21698
We have an explicit dependency on client_golang in the `require` section above, please change the dependency there.

2022-04-08 03:02 UTC, coreydaley commented on go.mod
> +	github.com/prometheus/client_golang => github.com/prometheus/client_golang v1.11.1 // CVE-2022-21698
updated, ptal

2022-04-08 13:58 UTC, coreydaley commented
/retest-required

2022-04-08 13:58 UTC, coreydaley commented
/skip

2022-04-08 17:04 UTC, gabemontero commented
/lgtm

2022-04-08 17:42 UTC, adambkaplan approved these changes
/approve

/lgtm

2022-04-08 17:46 UTC, merged